FROM nginx:1.20.1
RUN rm -rf /usr/share/nginx/html/* && rm -rf /etc/nginx/nginx.conf
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./dist/p2-frontend /usr/share/nginx/html
RUN chmod 644 /usr/share/nginx/html/*.*
EXPOSE 80
